StockIt.Mvc/Controllers/StockItemController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using StockIt.Core.Repositories.Locations;
using StockIt.Mvc.Models;
using StockIt.Mvc.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StockIt.Mvc.Controllers
{
    public class StockItemController : BaseController
    {
        private readonly ILocationDataService locationDataService;
        private readonly IStockItemDataService stockItemDataService;

        public StockItemController(ILocationDataService locationDataService, IStockItemDataService stockItemDataService)
        {
            this.locationDataService = locationDataService;
            this.stockItemDataService = stockItemDataService;
        }

        public async Task<IActionResult> Index()
        {
            var stockItems = await stockItemDataService.GetAllAsync(base.Tenant);

            return View(stockItems.FindAll(x => x.IsProcessed == false));
        }

        public async Task<IActionResult> Create()
        {
            var recievedStockItem = new StockItemViewModel
            {
                LocationList = new SelectList(await locationDataService.GetAllAsync(base.Tenant), "Id", "Name")
            };

            return View(recievedStockItem);
        }

        [HttpPost]
        public async Task<IActionResult> Create(StockItemViewModel recievedStockItemViewModel)
        {
            var locations = await locationDataService.GetAllAsync(base.Tenant);
            var item = recievedStockItemViewModel.ConvertToStockItem();
            item.Tenant = base.Tenant;
            item.Location = locations.FirstOrDefault(x => x.Id == item.LocationId).Name;
            await stockItemDataService.AddAsync(item);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(string id, string tenant)
        {
            var product = await stockItemDataService.GetAsync(id, tenant).ConfigureAwait(false);
            return View(product);
        }

        ////[HttpPost]
        ////public async Task<IActionResult> Delete(Stock product)
        ////{
        ////    await stockItemDataService.DeleteAsync(product.Id, base.Tenant).ConfigureAwait(false);
        ////    return RedirectToAction("Index", "Product");
        ////}

        ////public async Task<IActionResult> Edit(string id, string tenant)
        ////{
        ////    var product = await productDataService.GetAsync(id, tenant).ConfigureAwait(false);
        ////    return View(product);
        ////}
    }
}

StockIt.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StockIt.Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/a5eae8b8b9.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StockIt.Mvc</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StockItem" asp-action="Index">Stock Item</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Location" asp-action="Index">Locations</a>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li><a id="qsLogoutBtn" asp-controller="Account" asp-action="Logout">Logout</a></li>
                        }
                        else
                        {
                            <li><a id="qsLoginBtn" asp-controller="Account" asp-action="Login">Login</a></li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - StockIt.Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>